#!/bin/bash
make
./a.out $HOME/testcases/test1.tig
./a.out $HOME/testcases/test2.tig
./a.out $HOME/testcases/test3.tig
./a.out $HOME/testcases/test4.tig
./a.out $HOME/testcases/test5.tig
./a.out $HOME/testcases/test6.tig
./a.out $HOME/testcases/test7.tig
./a.out $HOME/testcases/test8.tig
./a.out $HOME/testcases/test9.tig
./a.out $HOME/testcases/test10.tig
./a.out $HOME/testcases/test11.tig
./a.out $HOME/testcases/test12.tig
./a.out $HOME/testcases/test13.tig
./a.out $HOME/testcases/test14.tig
./a.out $HOME/testcases/test15.tig
./a.out $HOME/testcases/test16.tig
./a.out $HOME/testcases/test17.tig
./a.out $HOME/testcases/test18.tig
./a.out $HOME/testcases/test19.tig
./a.out $HOME/testcases/test20.tig
./a.out $HOME/testcases/test21.tig
./a.out $HOME/testcases/test22.tig
./a.out $HOME/testcases/test23.tig
./a.out $HOME/testcases/test24.tig
./a.out $HOME/testcases/test25.tig
./a.out $HOME/testcases/test26.tig
./a.out $HOME/testcases/test27.tig
./a.out $HOME/testcases/test28.tig
./a.out $HOME/testcases/test29.tig
./a.out $HOME/testcases/test30.tig
./a.out $HOME/testcases/test31.tig
./a.out $HOME/testcases/test32.tig
./a.out $HOME/testcases/test33.tig
./a.out $HOME/testcases/test34.tig
./a.out $HOME/testcases/test35.tig
./a.out $HOME/testcases/test36.tig
./a.out $HOME/testcases/test37.tig
./a.out $HOME/testcases/test38.tig
./a.out $HOME/testcases/test39.tig
./a.out $HOME/testcases/test40.tig
./a.out $HOME/testcases/test41.tig
./a.out $HOME/testcases/test42.tig
./a.out $HOME/testcases/test43.tig
./a.out $HOME/testcases/test44.tig
./a.out $HOME/testcases/test45.tig
./a.out $HOME/testcases/test46.tig
./a.out $HOME/testcases/test47.tig
./a.out $HOME/testcases/test48.tig
./a.out $HOME/testcases/test49.tig
